name: Ping API Every Minute

on:
  schedule:
    - cron: '*/1 * * * *'  # Runs every minute

jobs:
  ping-api:
    runs-on: ubuntu-latest
    steps:
      - name: Make a request to the API
        run: |
          curl -X POST https://email-automator.fly.dev/process-email